### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 40tude2** [AVSGuillaume/Samples-Pack#3]
Je pense qu'il faut couvrir les exemples avec une licence et donc ajouter une fichier licence.md à la racine du repo
Je propose licence MIT

Exemple : 
https://choosealicense.com/licenses/mit/

**Comment by AVSGuillaume** [comment]
Etrangement l'article recommande BSD-2 qui est similaire à MIT, mais "moins ambigue"

Mais au contraire d'autres sources donnent MIT comme plus complète. Et effectivement ça l'est au moins pour moi. Notemment la permission explicite d'utiliser les sources et binaires pour marketing, et même revente.

J'inclus donc une license.md MIT sur la branche 2021.1
